[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"
skeletonBackgroundColor = "#1e293b"
base = "dark"

[server]
headless = true
